version: "3.8"

services:
  konga:
    image: konga:latest
    build: .
    restart: always
    container_name: konga
    ports:
      - 1337:1337
    environment:
      - NODE_ENV=development
      - DB_ADAPTER=postgres
      - DB_HOST=konga-database
      - DB_PORT=5432
      - DB_USER=konga
      - DB_PASSWORD=password
      - DB_DATABASE=konga
    volumes:
      - ./api/:/app/api/
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
      - konga-database
    entrypoint: ["npm", "start"]
  konga-database:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: konga
      POSTGRES_PASSWORD: password
      POSTGRES_DB: konga
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "konga"]
      interval: 5s
      timeout: 5s
      retries: 5